In [136]:
import pandas as pd 
import numpy as np
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from datetime import timedelta
geolocator = Nominatim(user_agent="myGeolocator", timeout=2)

# read the csv into a dataframe
# only import the columns we will use, so avoid spending time dropping 90 columns later
#df = pd.read_csv(('0714monm135536.csv'), usecols=['propertyLocation', 'ownersName', 'ownersMailingAddress', 'cityStateZip'])
df = pd.read_pickle('newark.pkl')
# after this initial instance, we'll read from the pickled dataframes
errors_df = pd.read_pickle('errors_newark.pkl')


# create a column for the owner's full mailing address
#df['ownersFullMailingAddress'] = df['ownersMailingAddress'] + ', ' + df.cityStateZip
# create a column for the property's full address
#df['propertyFullAddress'] = df.propertyLocation + ' Newark, NJ'

#df = pd.read_pickle('newark.pkl')
#errors_df = pd.read_pickle('errors_df.pkl')

# returns an array of properties associated with the owne
def getPropertiesOwned(owner=str):
    unique_properties = df[df.ownersName == owner]['propertyLocation'].unique()    
    return unique_properties.tolist()

# number of times property appears in first column
# I'm assuming this is one way to determine how many units
# are at a given address
def getUnits(address=str):
    return len(df[df.propertyLocation == address])

# number of the properties owned by the given owner
def getNumberOwned(owner=str):
    return df[(df.ownersName == owner)]['propertyLocation'].count()

In [137]:
df

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
0,1050-1052 MCCARTER HWY,SEABRA BROTHERS II,260CHESTNUT ST. 2ND FLOOR,"NEWARK, NJ 07105",1,[1050-1052 MCCARTER HWY],1,"1050-1052 MCCARTER HWY Newark, NJ","(1050, McCarter Highway, Newark, Essex County,..."
1,1155-1157 MCCARTER HWY,LEG 450 BROAD STREET LLC,283-299 MARKET ST,"NEWARK, NJ 07102",1,"[1155-1157 MCCARTER HWY, 2-28 DIVISION ST, 30-...",4,"1155-1157 MCCARTER HWY Newark, NJ","(McCarter Highway, Newark, Essex County, New J..."
2,23 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"23 BRIDGE ST Newark, NJ","(23, Bridge Street, Newark, Essex County, New ..."
3,25 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NY 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"25 BRIDGE ST Newark, NJ","(25, Bridge Street, Newark, Essex County, New ..."
4,27 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"27 BRIDGE ST Newark, NJ","(27, Bridge Street, Newark, Essex County, New ..."
...,...,...,...,...,...,...,...,...,...
23971,245 DR MARTIN LUTHER KING JR BLVD,"241 HIGH STREET LLC,",251 LITTLE FALLS DR,"WILMINGTON, DE 19808",1,[245 ML KING BLVD],1,"245 DR MARTIN LUTHER KING JR BLVD Newark, NJ","(245, Dr. Martin Luther King Jr. Boulevard, Ne..."
23972,247 DR MARTIN LUTHER KING JR BLVD,NJIT,UNIVERSITY HEIGHTS,"NEWARK, NJ 07102",1,"[5 GREEK WAY, 7 GREEK WAY, 9 GREEK WAY, 11 GRE...",15,"247 DR MARTIN LUTHER KING JR BLVD Newark, NJ","(247, Dr. Martin Luther King Jr. Boulevard, Ne..."
23973,247- DR MARTIN LUTHER KING JR BLVD,NJIT,UNIVERSITY HEIGHTS,"NEWARK,NJ, NY 07102",1,"[5 GREEK WAY, 7 GREEK WAY, 9 GREEK WAY, 11 GRE...",15,"247- DR MARTIN LUTHER KING JR BLVD Newark, NJ","(247, Dr. Martin Luther King Jr. Boulevard, Ne..."
23974,193-195 DR MARTIN LUTHER KING JR BLVD,NATIONAL FUEL OIL INC,175 ORANGE ST,"NEWARK, NJ 07103",1,"[193-195 ML KING BLVD, 197-199 ML KING BLVD]",2,"193-195 DR MARTIN LUTHER KING JR BLVD Newark, NJ","(193, Dr. Martin Luther King Jr. Boulevard, Ne..."
23975,197-199 DR MARTIN LUTHER KING JR BLVD,NATIONAL FUEL OIL INC,175 ORANGE ST,"NEWARK, NJ 07103",1,"[193-195 ML KING BLVD, 197-199 ML KING BLVD]",2,"197-199 DR MARTIN LUTHER KING JR BLVD Newark, NJ","(197, Dr. Martin Luther King Jr. Boulevard, Ne..."

In [140]:
errors_df.propertyLocation.unique()

array(['997-999 MCCARTER HWY', '609-625 BROAD ST', '538-546 BROAD ST',
       '450-466 BROAD STEAR', '138-162 DR MARTIN LUTHER KING JR BLVD',
       '915-933 BROAD ST', '284-292 HALSEY ST', '999-1005 BROAD ST',
       '961-985 BROAD ST', '987-997 BROAD ST', '10-14 W KINNEY PL',
       '442-448 WASHINGTON ST',
       '698-700 DR MARTIN LUTHER KING JR BLVD RE',
       '826-836 MCCARTER HWYEAR', '1111-1131 RAYMOND BLVD',
       '1172-1182 RAYMOND BLVD', '842-868 BROAD ST',
       '943-973 RAYMOND BLVD', '228-260 HUNTERDON ST', '276-292 15TH AVE',
       '313-329 15TH AVE', '302-324 SPRINGFIELD AVE',
       '374-374- S 10TH ST', '342-354 S 8TH ST', '307-321 S 7TH ST',
       '392-392- S 8TH ST', '307-347 LITTLETON AVE', '410-416 S 6TH ST',
       '392-398 S 6TH ST', '578-592 S 13TH', '581-593 S 12TH ST',
       '604-618 S 13TH', '594-602 S 13TH', '593-609 S 11TH ST',
       '594-602 S 12TH ST', '476-488 18TH AVE', '507-521 18TH AVE',
       '432-434 S 14TH', '428-430 S 14TH', '437-439 S 16TH S',
       '367-409 S 19TH ST', '458-462 S 16TH', '468-470 S 15TH S',
       '449-451 S 13TH', '495-497 S 13TH', '523-525 S 14TH',
       '522-526 S 15TH', '520-526 S 16TH S', '528-530 S 16TH',
       '538-540 S 16TH', '531-535 S 16TH S', '637-643 15TH AVE',
       '526-528 S 20TH', '609-611 S 19TH', '610-612 S 20TH',
       '604-606 S 20TH', '587-589 S SEVEN10TH', '592-594 S 18TH',
       '582-564 S 18TH', '640-642 S 19TH', '640-642 S 20TH',
       '618-620 S 20TH', '621-623 S 20TH', '643-645 S 20TH',
       '605-615 18TH AVE', '671--675 S 18TH', '597-601 18TH AVE',
       '673-675 S 17TH', '672-674 S 16TH S', '651-653 S 14TH',
       '673-675 S 14TH', '685-687 S 14TH', '625-641 S 13TH',
       '732-734 S 18TH', '720-722 S 18TH', '748-750 S 19TH',
       '749-751 S 19TH', '766 S 20TH', '732-734 S 20TH',
       '224-252 CENTRAL AVE', '81 C0SSIO DR', '257-295 WARREN ST',
       '173-229 NORFOLK ST', '264-304 PASSAIC ST',
       '1374-1398 MCCARTER HWY', '1300-1328 MCCARTER HWY',
       '1330-1346 MCCARTER HWY', '252A-252B CLIFTON AVE',
       '190-210 CLIFTON AVE', '159 SUMMER AVEEAR', '165 SUMMER AVEEAR',
       '1485-1487 MCCARTER HWY', '448-452 N 13TH', '432-434 N 13TH',
       '428-430 N 13TH', '424-426 N 13TH', '420-422 N 13TH',
       '425-427 N 13TH', '439-441 N 13TH', '443-445 N 13TH',
       '449-451 N 13TH', '592-94 N 6TH ST', '497-503 LAKE ST',
       '478-482 CLIFTON AVE', '398-406 MT PROSPECT AVE',
       '378-396 MT PROSPECT AVE', '379-387 MT PROSPECT AVE',
       '363-377 MT PROSPECT AVE', '1694-1700 MCCARTER HWY',
       '42-44 CHESTER AVE', '50-52 CHESTER AVE', '58-60 CHESTER AVE',
       '122 CHESTER AVE', '120 CHESTER AVE', '118 CHESTER AVE',
       '110 CHESTER AVE', '108 CHESTER AVE', '132 CHESTER AVE',
       '130 CHESTER AVE', '412-644 N 6TH ST', '151-623 N 7TH ST',
       '496-498 N 13TH', '484-486 N 13TH', '478-480 N 13TH',
       '510-512 N 13TH', '516-518 N 13TH', '532-534 N 13TH', '532 N 13TH',
       '516-18 N 13TH', '510-12 N 13TH', '515-517 N 13TH',
       '214-220 BALLANTINE PKW', '31-33 CHESTER AVE', '55 CHESTER AVE',
       '559-561 BROADWAY, REAR', '110-114 DELAVAN AVE ,E',
       '119 CHESTER AVE', '543-563 MT PROSPECT AVE', '526-532 RIDGE ST',
       '292-300 DELAVAN AVE  E', '458-462 HIGHLAND AVE',
       '776-784 N 6TH ST', '254-256 ELWOOD AVE  E', '655-661 LAKE ST',
       '267-271 DELAVAN AVE  E', '584-588 RIDGE ST', '576-582 RIDGE ST',
       '554-562 RIDGE ST', '666-672 CLIFTON AVE', '659-665 CLIFTON AVE',
       '169-171 DELAVAN AVE  E', '177-179 DELAVAN AVE  E',
       '563-563- SUMMER AVE', '584-586 BROADWAY', '637-647 SUMMER AVE',
       '252 W00DSIDE AVE', '569-573 HIGHLAND AVE', '292-324 GRAFTON AVE',
       '100-102 FOREST HILL PK', '772-776 DEGRAW AVE',
       '766-770 DEGRAW AVE', '71 FOREST HILL CONDO',
       '77 FOREST HILL CONDO', '768-772 CLIFTON AVE', '62-64 ELLIOT ST',
       '54 ELLIOT ST', '50-52 ELLIOT ST', '38-40 ELLIOT ST',
       '31-33 ELLIOT ST', '793-799 BROADWAY', '770-778 MT PROSPECT AVE',
       '655-661 HIGHLAND AVE', '827-831 LAKE ST', '682-686 HIGHLAND AVE',
       '25 MNCHESTER PL', '2 MANCHESTRER PL', '47 BRANCH BROOK NY',
       '864-888 N 7TH ST', '896-898 DEGRAW AVE', '896-898 LAKE ST',
       '863-867 DEGRAW AVE', '871-873 LAKE ST', '897-901 LAKE ST',
       '888-890 CLIFTON AVE', '878-882 CLIFTON AVE', '786-802 SUMMER AVE',
       '786-802 SUMMER', '802-812 BROADWAY', '22-26 IRVING STEAR',
       '2078-2090 MCCARTER HWY', '792-820 HIGHLAND AVE', '72 COLOMBIA ST',
       '1056-1070 BROAD ST', '115 ORCHARD STEAR', '1098-1102 BROAD ST',
       '233 NO 4TH ST', '164-184 PENNINGTON ST', '226-226- CHESTNUT ST',
       '96 CLIFORD ST', '18 HENNESY ST', '20 HENNESY ST', '22 HENNESY ST',
       '9 HENNESY ST', '101 GARRISON STEAR', '612-104 JABEZ ST',
       'VARNUM ST', '27-29 WHEELR PT RD', '344-356 THOMAS ST',
       '358-366 THOMAS ST', '205-207 VANDERPOL ST',
       '557 SOUTH ORNAGE AVE', '335-337 S 20TH', '359-361 S 18TH',
       '363-365 S 18TH', '390-390- S 19TH ST', '372-374 S 19TH',
       '372-374 S 20TH', '368-370 S 20TH', '308-310 S 19TH',
       '317-319 S 19TH', '112 ELEVENTH AVE', '201 S 10TH STEAR',
       '203 S 10TH STEAR', '279-281 S 19TH', '241-243 18TH ST',
       '249--251 S 18TH', '478-492 CENTRAL AVE', '392-414 WEST MARKET ST',
       '103-105 S 12TH', '573-581 CENTRAL AVE', '118-120 S 13TH',
       '108-110 S 13TH', '118-120 S 14TH', '135-137 S 13TH',
       '115-117 S 14TH', '118-120 S 15TH S', '110-112 S 15TH S',
       '73-75 S 13TH S', '391-397 SUSSEX AVE', '589-599 WEST MARKET ST',
       '553-567 ORANGE ST', 'BLDG551 ORANGE ST', '175-199 1ST ST',
       '322-330 6TH AVE', '475-479 7TH AVE', '128-130 N 13TH',
       '351-365 6TH AVE', '103-121 N 13TH', '159-189 N 13TH ST',
       '203-205 N 13TH', '23-25 SPRINGDALE AVEEAR',
       '355-357 ORTH 12TH ST', '467-479 ROSEVILLE AVE', '243 2ND AVEEST',
       '233-135 ADAMS ST', '584-586 MARKET ST', '681-681- MARKET ST',
       '596-610 RAYMOND BLVD', '17-21 PATERSON ST H1', '9 ALYEA STEAR',
       '726-740 FERRY ST', '335-347 RAYMOND BLVD', '2-10 LISTER AVEEAR',
       '94-102 LISTER AVEEAR', '86-92 LISTER AVE  REAR',
       '86-92 LISTER AVEEAR', '413-433 RAYMOND BLVD R',
       '32-34 CHAPEL STEAR', '10 HORATIOST', '124-132 COURT STEAR',
       '607-639 DR MARTIN LUTHER KING JR BLVD', '8-24 DOLBY PL',
       '671-683 DR MARTIN LUTHER KING JR BLVD',
       '685-715 DR MARTIN LUTHER KING JR BLVD', '273-277 PRINCE ST',
       '203-227 CHARLTON ST', '291-319 18TH AVE',
       '221-305 IRVINE TURNER BLV', '387-391 18TH AVE', '757-759 S 14TH',
       '752 S FIFTEETH ST', '780-782 S 16TH', '717- S 15TH STEAR',
       '753-755 S 16TH', '753-755 S 17TH', '768-770 S 18TH',
       '764-766 SO 18TH', '756-762 S 18TH', '776-780 S 19TH',
       '791-793 S 18TH', '504-512 AVON AVE', '839-841 S 19TH',
       '843-845 S 19TH', '813-815 S 18TH', '819-821 S 18TH',
       '818-820 S 19TH', '813-815 S 17TH', '845 S SEVNTEENTH ST',
       '822-826 S 18TH', '818-820 S 17TH', '842-844 S 16TH',
       '813-815 S 14TH', '791-793 S 13TH', '813-815 S 13TH',
       '798-800 S 14TH', '810-812 S 13TH', '816-18 S 13TH',
       '782-788 S 10TH ST', '545-557 BERGEN ST', '584-586 BERGEN ST',
       '397-403 IRVINE TURNER BLV', '611-635 BERGEN ST',
       '416-432 IRVINE TURNER BLV', '510-512 IRVINE TURNER BL',
       '514-516 IRVINE TURNER BL', '747-773 BERGEN ST',
       '1183-1185 BROAD ST', '297- M L KING BLVD', '65-71 NORFLOK ST',
       '860-868 S 11TH ST', '667-671 CLINTON AVE', '861-865 S 11TH ST',
       '872-878 S 13TH', '868-870 S 13TH', '848-850 S 13TH',
       '866-868 S 14TH', '823-825 S 13TH', '865-867 S 13TH',
       '839-841 S 14TH', '843-845 S 14TH', '881-883 S 14TH',
       '888-890 S 15TH', '831-835 S 15TH ST', '881-883 S 15TH S',
       '908-910 S 16TH', '896-898 S 16TH ST', '888-890 S 16TH',
       '881-885 S 16TH', '895-897 S 16TH', '901-903 S 16TH',
       '907-909 S 16TH S', '918-920 S 17TH', '906-908 S 17TH',
       '898-900 S 17TH ST', '866-868 S 17TH', '923-925 S 16TH',
       '871-873 S 17TH', '881-883 S 17TH', '893-895 S 17TH',
       '901-903 S 17TH', '905-907 S 17TH', '909-911 S 17TH',
       '930-932 S 18TH', '878-880 S 18TH', '862-864 S 18TH',
       '858-860 S 18TH', '881-883 S 18TH', '895-897 S 18TH',
       '870-874 S 19TH', '901-903 S 19TH', '889-891 S 19TH',
       '937-939 S 20TH', '921-923 S 19TH', '925-927 S 19TH',
       '937-939 S 19TH', '926-928 S 20TH', '181 SEYMOUR ST',
       '570-580 CLINTON AVE', '293-303 HAWTHORNE AVE',
       '634-648 CLINTON AVE', '696-702 CLINTON AVE',
       '686-690 CLINTON AVE', '17-19 CLNTON PL', '55 HOMESTEAD PARK',
       '47-49 HOMESTEAD PARK', '33-35 HOMESTEAD PARK',
       '1-3 HOMESTEAD PARK ROA', '59-61 HOMESTEAD PARK',
       '22-24 HOMESTEAD PARK', '26-28 HOMESTEAD PARK',
       '30-32 HOMESTEAD PARK', '34-36 HOMESTEAD PARK',
       '38-40 HOMESTEAD PARK', '42-44 HOMESTEAD PARK',
       '48-56 HOMESTEAD PARK', '60-62 HOMESTEAD PARK',
       '29 ST JAMES PL REAR', '1-13 SARAH VAUGHAN PL',
       '285-287 FRELINGHYSEN AVE', '415-433 ELIZABETH AVE',
       '671-689 IRVINE TURNER BLV', '443-461 ELIZABETH AVE',
       '463-473 ELIZABETH AVE', '824-838 BERGEN ST',
       '807-837 HUNTERDON ST', '136-338 CLINTON PL',
       '489-505 ELIZABETH AVE', '167 MAPE AVE.', '775-781 ELIZABETH AVE',
       '795-809 ELIZABETH AVE', '1157-1165 BERGEN ST',
       '377-383 CLINTON PL', '344-368 FABYAN PL', '371-73 WAINWRIGHT ST',
       '385- WAINWRIGHT STEAR', '343-381 SCHLEY ST', '1576 SCHLEY STEAR',
       '554-566 SOUTH ORANGE AVE', '572-588 SOUTH ORANGE AVE',
       '391-419 GROVE ST', '981-983 18TH AVE', '34-36 BOYLAND ST',
       '54-74 BROOKDALE AVEEAR', '10 NORWOOD STEAR',
       '698-716 SANFORD AVE', '638-644 SANFORD AVE', '1067-1069 18TH AVE',
       '153-157 STUYVSNT AVE', '1072-1074 18TH AVE',
       '584-586 SANFORD AVE', '508-512 SANFORD AVE',
       '59-61 HAZELLWOOD AVE', '208 ELLERY AVEEAR', '8 MONTROSE STEAR',
       '10 MONTROSE STEAR', '310 SANFORD STEAR', '71-73 HALSTED ST',
       '67-69 HALSTED ST', '63-65 HALSTED ST', '51-53 HALSTED ST',
       '43-45 HALSTED ST', '39-41 HALSTED ST', '37 HALSTED ST',
       '23 HALSTED ST', '19-21 HALSTED ST', '15-17 HALSTED ST',
       '11 HALSTED ST', '83-85 HALSTED ST', '115-117 HALSTED ST',
       '92-94 HALSTED ST', '112-122 HALSTED ST', '76-78 HALSTED ST',
       '74 HALSTED ST', '70-72 HALSTED ST', '66-68 HALSTED ST',
       '62-64 HALSTED ST', '58-60 HALSTED ST', '54-56 HALSTED ST',
       '46-48 HALSTED ST', '36-38 HALSTED ST', '32 HALSTED ST',
       '28-30 HALSTED ST', '17 TREMONT AVEEAR', '19 TREMONT AVEEAR',
       '27 TREMONT AVEEAR', '36 CHELSEA AVEEAR', '97-99 NORMAN PL',
       '238-254 MT VERNON PL', '475-487 IRVINGTON AVE',
       '212-236 MT VERNON PL', '192-210 MT VERNON PL',
       '489-559 IRVINGTON AVE', '142-144 MILAND PL', '309-211 MIDLAND PL',
       '609-631 IRVINGTON AVE', '27-117 RAYMOND BLVD REAR',
       '139-155 RAYMOND BLVDREAR', '157-161 RAYMOND BLVD REAR',
       '151-155 RAYMOND BLVD REAR', '1-25 RAYMOND BLVD REAR',
       '1-27 RAYMOND BLVD REAR', '18-36 BLANCHARD STEAR',
       '66-68 BLANCHARD STEAR', '183-201 RAYMOND BLVD',
       '104-128 FOUNDRY STEAR', '219-221 FOUNDRY STEAR',
       '187-191 FOUNDRY STEAR', '195-217 FOUNDRY STEAR',
       '279-295 DOREMUS AVE', '191-269 DOREMUS AVEEAR',
       '191-269 DOREMUS AVE', '173-269 DOREMUS AVE', '291-307 AVENUE P',
       '309-327 AVENUE P', '309-327 AVENUE P REAR', '357-383 AVENUE P',
       '105-135 HYATT LN', '161 HYATT LN', '551 AVENUE P REAR',
       '385-405 AVENUE P', '21 HYATT AVEEAR', '357-391 WILSON AVE',
       'RICHARDS LN REAR', '357-391 WILSON AVEEAR', '391-505 DELANCY ST',
       '507-543 DELANCY ST', '121-137 AVENUE I REAR', '121 AVENUE I REAR',
       '547-595 DELANCY ST', '421-447 DOREMUS AVEEAR',
       '376-394 DOREMUS AVEEAR', '396-414 DOREMUS AVEEAR',
       '282 DOREMUS AVEEAR', '740-768 DOREMUS AVE', '921-979 DELANCY ST',
       '848-850 DOREMUS AVEEAR', '852 DOREMUS AVEEAR',
       '940-964 DOREMUS AVE', '935-963 DOREMUS AVEEAR',
       '847-983 DOREMUS AVE', '859-933 DOREMUS AVEEAR',
       '847-857 DOREMUS AVEEAR', '250 PORT STEAR', '857 DOREMUS AVEEAR',
       '70 PORT STEAR', '20 PORT STEAR', '220-230 PORT STEAR',
       '228-230 PORT STEAR', '86-144 HAYNES AVEEAR', '373-395 S ST',
       '386-406 RT 1 & 9', '362-384 RT 1 & 9', '106-132 RT 1 & 9',
       '314-332 RT 1 & 9'], dtype=object)

In [71]:
# df['units'] = [getUnits(address) for address in df.propertyLocation]
# df['propertiesOwned'] = [getPropertiesOwned(owner) for owner in df.ownersName]
# df['numberPropertiesOwned'] = [getNumberOwned(owner) for owner in df.ownersName]
# df['propertyFullAddress'] = df.propertyLocation + ' Newark, NJ'

#len(df['propertyFullAddress'].unique())
# df['gCode'] = df.propertyFullAddress.apply(geolocator.geocode)
#geocode_errors = [i for i,e in enumerate(df.gCode) if e == None]
#errors_df = df.iloc[geocode_errors].copy()

In [109]:
#df.dropna(axis=0, subset=['gCode'], inplace=True)
#df.to_pickle('newark.pkl')
#errors_df.to_pickle('errors_df.pkl')

In [131]:
#errors_df.propertyLocation = errors_df.propertyLocation.str.replace('MCWHORTER', 'MC WHORTER')
#errors_df.propertyLocation = errors_df.propertyLocation.str.replace('ML KING', 'DR MARTIN LUTHER KING')
#errors_df.propertyLocation = errors_df.propertyLocation.str.replace('DR MARTIN LUTHER KING', 'DR MARTIN LUTHER KING JR')

# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('SCOFIELD', 'SCHOFIELD')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('STECHER', 'STETCHER')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('PARK VIEW', 'PARKVIEW')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('SANDFORD', 'SANFORD')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('VAL SUMO', 'VALSUMO')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('PATTERSON', 'PATERSON')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('AVE E', 'AVE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('13COLGATE', '13 COLGATE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('MOUNTAIN VIEW', 'MOUNTAINVIEW')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('DE GRAW', 'DEGRAW')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('GOTTHART', 'GOTTHARDT')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('AVE W', 'AVE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('ST AR', 'ST')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('BLVD AR', 'BLVD')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('AVE AR', 'AVE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('NJRR', 'New Jersey Railroad')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('HWY AR', 'HWY')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('PL AR', 'PL')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('LN AR', 'LN')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('HOMESTEAD PK RD', 'HOMESTEAD PARK RD')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('13TH R', '13TH')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('HWY R', 'HWY')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('AVE R', 'AVE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('ST R', 'ST')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('AVE,', 'AVE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('AVE  AR', 'AVE')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('ELVENTH', 'ELEVENTH')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('THRITEENTH R', '13TH ST')
# errors_df.propertyLocation = errors_df.propertyLocation.str.replace('PKWAY', 'PKWY')

errors_df.propertyLocation = errors_df.propertyLocation.str.replace(r'-\d{1,4}', '')

errors_df['propertyFullAddress'] = errors_df.propertyLocation + ' Newark, NJ'

In [132]:
errors_df['gCode'] = errors_df.propertyFullAddress.apply(geolocator.geocode)

In [133]:
geocode_errors = [i for i,e in enumerate(errors_df.gCode) if e == None]

In [134]:
errors_df.iloc[geocode_errors]

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
12,997-999 MCCARTER HWY,ELLER OUTDOOR ADV UNITED DIVISION,185U US HIGHWAY 46,"FAIRFIELD, NJ 07004",1,"[997-999 MCCARTER HWY, 740-742 MCCARTER HWY]",2,"997-999 MCCARTER HWY Newark, NJ",None
16,609-625 BROAD ST,"609 BROAD STREET LLC,",1865 PALMER AVE,"LARCHMONT, NY 10538",1,[609-625 BROAD ST],1,"609-625 BROAD ST Newark, NJ",None
22,538-546 BROAD ST,"540 BROAD ST OWNERS, LLC","2 PARK AVENUE, 23RD FL.","NEW YORK, NY 10016",1,[538-546 BROAD ST],1,"538-546 BROAD ST Newark, NJ",None
23,450-466 BROAD STEAR,"LEG 450 BROAD STREET, LLC",675 THIRD AVE 28TH FL,"NEW YORK, NY 10017",1,[450-466 BROAD ST REAR],1,"450-466 BROAD STEAR Newark, NJ",None
134,138-162 DR MARTIN LUTHER KING JR BLVD,"PAVILION TOWERS, LLC,",35 JOURNAL SQUARE 4TH FL,"JERSEY CITY, NJ 07306",1,"[166-174 ML KING BLVD, 138-162 ML KING BLVD, 1...",3,"138-162 DR MARTIN LUTHER KING JR BLVD Newark, NJ",None
...,...,...,...,...,...,...,...,...,...
34676,373-395 S ST,"VERNEWARK ASSOCIATES,LLC",401 SOUTH ST.,"NEWARK, NJ 07105",1,[373-395 S ST R],1,"373-395 S ST Newark, NJ",None
34683,386-406 RT 1 & 9,"CFS 2907 NEWARK SKYP,C/O RYAN",600 5TH AVE. 9TH FL,"NEW YORK, NY 10020",1,"[386-406 RT 1 & 9, 362-384 RT 1 & 9]",2,"386-406 RT 1 & 9 Newark, NJ",None
34684,362-384 RT 1 & 9,"CFS 2907 NEWARK SKYP,C/O RYAN",600 5TH AVE 9TH FL,"NEW YORK, NY 10020",1,"[386-406 RT 1 & 9, 362-384 RT 1 & 9]",2,"362-384 RT 1 & 9 Newark, NJ",None
34685,106-132 RT 1 & 9,CFS2907 NWK MCLELLAN LLC C/O RYAN,600 5TH AVE. 9TH FL,"NEW YORK, NY 10020",1,[106-132 RT 1 & 9],1,"106-132 RT 1 & 9 Newark, NJ",None
34686,314-332 RT 1 & 9,ANHEUSER-BUSCH INC (CORP. TAX DEPT),1 BUSCH PL,"SAINT LOUIS, MO 63118",1,[314-332 RT 1 & 9],1,"314-332 RT 1 & 9 Newark, NJ",None

In [135]:
#non NA values appened to the dataframe and then pickled
df.append(errors_df.dropna(axis=0, subset=['gCode'])).to_pickle('newark.pkl')
# writing over the old errors_df
errors_df = errors_df.iloc[geocode_errors].copy()
# saving the new errors_df
errors_df.to_pickle('errors_newark.pkl')

In [79]:
first_cleaning = timedelta(seconds=17439)
second_cleaning = timedelta(seconds=819.5)

In [95]:
geocode_errors = [i for i,e in enumerate(errors_df.gCode) if e == None]
errors_df.iloc[geocode_errors]

Empty DataFrame
Columns: [propertyLocation, ownersName, ownersMailingAddress, cityStateZip, units, propertiesOwned, numberPropertiesOwned, propertyFullAddress, gCode]
Index: []

In [86]:
errors_df.iloc[[i for i,e in enumerate(errors_df.gCode) if e != None]] == errors_df.dropna(axis=0, subset=['gCode'])

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
522,True,True,True,True,True,True,True,True,True
523,True,True,True,True,True,True,True,True,True
524,True,True,True,True,True,True,True,True,True
525,True,True,True,True,True,True,True,True,True
730,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
34501,True,True,True,True,True,True,True,True,True
34502,True,True,True,True,True,True,True,True,True
34503,True,True,True,True,True,True,True,True,True
34504,True,True,True,True,True,True,True,True,True
34677,True,True,True,True,True,True,True,True,True

In [100]:
df

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
0,1050-1052 MCCARTER HWY,SEABRA BROTHERS II,260CHESTNUT ST. 2ND FLOOR,"NEWARK, NJ 07105",1,[1050-1052 MCCARTER HWY],1,"1050-1052 MCCARTER HWY Newark, NJ","(1050, McCarter Highway, Newark, Essex County,..."
1,1155-1157 MCCARTER HWY,LEG 450 BROAD STREET LLC,283-299 MARKET ST,"NEWARK, NJ 07102",1,"[1155-1157 MCCARTER HWY, 2-28 DIVISION ST, 30-...",4,"1155-1157 MCCARTER HWY Newark, NJ","(McCarter Highway, Newark, Essex County, New J..."
2,23 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"23 BRIDGE ST Newark, NJ","(23, Bridge Street, Newark, Essex County, New ..."
3,25 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NY 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"25 BRIDGE ST Newark, NJ","(25, Bridge Street, Newark, Essex County, New ..."
4,27 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"27 BRIDGE ST Newark, NJ","(27, Bridge Street, Newark, Essex County, New ..."
...,...,...,...,...,...,...,...,...,...
34710,21-23 GARIBALDI AVE,"PAULO,M. JIMMY & SUSAN",445 KING GEORGE RD,"BASKING RIDGE, NJ 07920",1,[21-23 GARIBALDI AVE],1,"21-23 GARIBALDI AVE Newark, NJ","(21, Garibaldi Avenue, Newark, Essex County, N..."
34711,25-27 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"25-27 GARIBALDI AVE Newark, NJ","(25, Garibaldi Avenue, Newark, Essex County, N..."
34712,29 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"29 GARIBALDI AVE Newark, NJ","(29, Garibaldi Avenue, Newark, Essex County, N..."
34713,31 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"31 GARIBALDI AVE Newark, NJ","(31, Garibaldi Avenue, Newark, Essex County, N..."
34714,33-41 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"33-41 GARIBALDI AVE Newark, NJ","(33, Garibaldi Avenue, Newark, Essex County, N..."

In [87]:
df.append(errors_df.dropna(axis=0, subset=['gCode'], inplace=True))

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
0,1050-1052 MCCARTER HWY,SEABRA BROTHERS II,260CHESTNUT ST. 2ND FLOOR,"NEWARK, NJ 07105",1,[1050-1052 MCCARTER HWY],1,"1050-1052 MCCARTER HWY Newark, NJ","(1050, McCarter Highway, Newark, Essex County,..."
1,1155-1157 MCCARTER HWY,LEG 450 BROAD STREET LLC,283-299 MARKET ST,"NEWARK, NJ 07102",1,"[1155-1157 MCCARTER HWY, 2-28 DIVISION ST, 30-...",4,"1155-1157 MCCARTER HWY Newark, NJ","(McCarter Highway, Newark, Essex County, New J..."
2,23 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"23 BRIDGE ST Newark, NJ","(23, Bridge Street, Newark, Essex County, New ..."
3,25 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NY 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"25 BRIDGE ST Newark, NJ","(25, Bridge Street, Newark, Essex County, New ..."
4,27 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"27 BRIDGE ST Newark, NJ","(27, Bridge Street, Newark, Essex County, New ..."
...,...,...,...,...,...,...,...,...,...
34710,21-23 GARIBALDI AVE,"PAULO,M. JIMMY & SUSAN",445 KING GEORGE RD,"BASKING RIDGE, NJ 07920",1,[21-23 GARIBALDI AVE],1,"21-23 GARIBALDI AVE Newark, NJ","(21, Garibaldi Avenue, Newark, Essex County, N..."
34711,25-27 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"25-27 GARIBALDI AVE Newark, NJ","(25, Garibaldi Avenue, Newark, Essex County, N..."
34712,29 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"29 GARIBALDI AVE Newark, NJ","(29, Garibaldi Avenue, Newark, Essex County, N..."
34713,31 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"31 GARIBALDI AVE Newark, NJ","(31, Garibaldi Avenue, Newark, Essex County, N..."
34714,33-41 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"33-41 GARIBALDI AVE Newark, NJ","(33, Garibaldi Avenue, Newark, Essex County, N..."

In [88]:
df.to_pickle('newark.pkl')

In [89]:
df = pd.read_pickle('newark.pkl')

In [90]:
df

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
0,1050-1052 MCCARTER HWY,SEABRA BROTHERS II,260CHESTNUT ST. 2ND FLOOR,"NEWARK, NJ 07105",1,[1050-1052 MCCARTER HWY],1,"1050-1052 MCCARTER HWY Newark, NJ","(1050, McCarter Highway, Newark, Essex County,..."
1,1155-1157 MCCARTER HWY,LEG 450 BROAD STREET LLC,283-299 MARKET ST,"NEWARK, NJ 07102",1,"[1155-1157 MCCARTER HWY, 2-28 DIVISION ST, 30-...",4,"1155-1157 MCCARTER HWY Newark, NJ","(McCarter Highway, Newark, Essex County, New J..."
2,23 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"23 BRIDGE ST Newark, NJ","(23, Bridge Street, Newark, Essex County, New ..."
3,25 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NY 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"25 BRIDGE ST Newark, NJ","(25, Bridge Street, Newark, Essex County, New ..."
4,27 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"27 BRIDGE ST Newark, NJ","(27, Bridge Street, Newark, Essex County, New ..."
...,...,...,...,...,...,...,...,...,...
34710,21-23 GARIBALDI AVE,"PAULO,M. JIMMY & SUSAN",445 KING GEORGE RD,"BASKING RIDGE, NJ 07920",1,[21-23 GARIBALDI AVE],1,"21-23 GARIBALDI AVE Newark, NJ","(21, Garibaldi Avenue, Newark, Essex County, N..."
34711,25-27 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"25-27 GARIBALDI AVE Newark, NJ","(25, Garibaldi Avenue, Newark, Essex County, N..."
34712,29 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"29 GARIBALDI AVE Newark, NJ","(29, Garibaldi Avenue, Newark, Essex County, N..."
34713,31 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"31 GARIBALDI AVE Newark, NJ","(31, Garibaldi Avenue, Newark, Essex County, N..."
34714,33-41 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"33-41 GARIBALDI AVE Newark, NJ","(33, Garibaldi Avenue, Newark, Essex County, N..."

In [78]:
errors_df['gCode'] = errors_df.propertyFullAddress.apply(geolocator.geocode)

In [ ]:
df.dropna(axis=0, subset=['gCode'], inplace=True)

In [ ]:
df

,propertyLocation,ownersName,ownersMailingAddress,cityStateZip,units,propertiesOwned,numberPropertiesOwned,propertyFullAddress,gCode
0,1050-1052 MCCARTER HWY,SEABRA BROTHERS II,260CHESTNUT ST. 2ND FLOOR,"NEWARK, NJ 07105",1,[1050-1052 MCCARTER HWY],1,"1050-1052 MCCARTER HWY Newark, NJ","(1050, McCarter Highway, Newark, Essex County,..."
1,1155-1157 MCCARTER HWY,LEG 450 BROAD STREET LLC,283-299 MARKET ST,"NEWARK, NJ 07102",1,"[1155-1157 MCCARTER HWY, 2-28 DIVISION ST, 30-...",4,"1155-1157 MCCARTER HWY Newark, NJ","(McCarter Highway, Newark, Essex County, New J..."
2,23 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"23 BRIDGE ST Newark, NJ","(23, Bridge Street, Newark, Essex County, New ..."
3,25 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NY 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"25 BRIDGE ST Newark, NJ","(25, Bridge Street, Newark, Essex County, New ..."
4,27 BRIDGE ST,"ALS NEWARK LLC,",494 BROAD ST SUITE 210,"NEWARK, NJ 07102",1,"[23 BRIDGE ST, 25 BRIDGE ST, 27 BRIDGE ST]",3,"27 BRIDGE ST Newark, NJ","(27, Bridge Street, Newark, Essex County, New ..."
...,...,...,...,...,...,...,...,...,...
34710,21-23 GARIBALDI AVE,"PAULO,M. JIMMY & SUSAN",445 KING GEORGE RD,"BASKING RIDGE, NJ 07920",1,[21-23 GARIBALDI AVE],1,"21-23 GARIBALDI AVE Newark, NJ","(21, Garibaldi Avenue, Newark, Essex County, N..."
34711,25-27 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"25-27 GARIBALDI AVE Newark, NJ","(25, Garibaldi Avenue, Newark, Essex County, N..."
34712,29 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"29 GARIBALDI AVE Newark, NJ","(29, Garibaldi Avenue, Newark, Essex County, N..."
34713,31 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"31 GARIBALDI AVE Newark, NJ","(31, Garibaldi Avenue, Newark, Essex County, N..."
34714,33-41 GARIBALDI AVE,"LUSA ENTERPRISE, INC",52-54 PORETE AVE,"NORTH ARLINGTON, NJ 07031",1,"[39-41 PERSHING AVE, 43-53 PERSHING AVE, 28-32...",9,"33-41 GARIBALDI AVE Newark, NJ","(33, Garibaldi Avenue, Newark, Essex County, N..."

In [ ]:
errors_df.to_pickle('errors_newark.pkl')

In [ ]:
#errors_df['propertyFullAddress'] = errors_df.propertyLocation + ' Newark, NJ'

In [ ]:
df.append(errors_df.dropna(axis=0, subset=['gCode']))

In [ ]:
errors_df = errors_df.iloc[geocode_errors].copy()

In [ ]:
errors_df['gCode'] = errors_df.propertyFullAddress.apply(geolocator.geocode)

In [ ]:
geocode_errors = [i for i,e in enumerate(errors_df.gCode) if e == None]

In [ ]:
errors_df.iloc[geocode_errors]['propertyLocation']

2455          594 S 13TH
2957        520 S 16TH S
3102     587 S SEVEN10TH
3461          766 S 20TH
3503         5 GREEK WAY
              ...
34662      857 DOMUS AVE
34683       386 RT 1 & 9
34684       362 RT 1 & 9
34685       106 RT 1 & 9
34686       314 RT 1 & 9
Name: propertyLocation, Length: 183, dtype: object

In [ ]:
errors_df.to_pickle('errors_df.pkl')